@host = http://localhost:8088
@contentType = application/json

# @name login
POST {{host}}/api/v1/auth/login
Content-Type: {{contentType}}

{
  "username": "admin",
  "password": "admin123"
}

###

@token = {{login.response.body.token}}

# @name createCustomer
POST {{host}}/api/v1/customers
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "name": "Diana Prince",
  "document": "44444444444",
  "birthDate": "1992-07-21",
  "email": "diana.prince@example.com"
}

###

GET {{host}}/api/v1/customers?page=0&size=10
Authorization: Bearer {{token}}

###

GET {{host}}/api/v1/customers?name=diana&page=0&size=10
Authorization: Bearer {{token}}

###

@customerId = {{createCustomer.response.body.id}}

GET {{host}}/api/v1/customers/{{customerId}}
Authorization: Bearer {{token}}

###

PUT {{host}}/api/v1/customers/{{customerId}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "name": "Diana Prince Updated",
  "document": "44444444444",
  "birthDate": "1992-07-21",
  "email": "diana.prince@example.com"
}

###

DELETE {{host}}/api/v1/customers/{{customerId}}
Authorization: Bearer {{token}}
